export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SELECTED_EDITED_PRODUCT: "SELECTED_EDITED_PRODUCT",
  SELECTED_BUY_PRODUCT: "SELECTED_BUY_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  CONTACT_INFO: "CONTACT_INFO",
};
